### ISSUE TITLE
trotz nicht vorhandener Berechtigungen Menü-Punkt sichtbar

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/geolocation#111]
Weder die Tables sind in irgend einer Form freigegeben, noch die spezifischen geolocation-Einzelberechtigungen. Dennoch sieht der User das:

![Screenshot 2022-12-08 150313](https://user-images.githubusercontent.com/7023022/206466291-9ab4a708-04a3-4cd9-982b-25f16db980e3.png)

Klickt der Nutzer dort drauf, kommt:

![image](https://user-images.githubusercontent.com/7023022/206466421-b51362cb-fe35-4769-acfc-f1e53ba35c1e.png)

**Comment by christophboecker** [comment]
Danke für den Hinweis, Peter. Ich hab mal das hier ausprobiert, also oben bei der Hauptseite ein `perm: geolocation[]` eingebaut. Ohne diese Berechtigung ist auch der Eintrag links im Menü weg. 
```yml
page:
    title: translate:geolocation_title
    pjax: true
    icon: rex-icon fa-globe
    perm: geolocation[]
    subpages:
        config:
            title: translate:geolocation_config
            icon: fa fa-wrench
            perm: 'admin[]'
        mapset:
            title: translate:geolocation_mapset
            perm: 'geolocation[mapset]'
            icon: fa fa-map
            subPath: pages/yform.php
        layer:
            title: translate:geolocation_layer
            perm: 'geolocation[layer]'
            icon: fa fa-cloud-download
            subPath: pages/yform.php
        docs:
            title: translate:geolocation_manpage
            icon: fa fa-book
            subPath: help.php
        clear_cache:
            title: 'translate:geolocation_clear_cache'
            perm: 'geolocation[clearcache]'
            itemclass: pull-right
            linkclass: 'btn btn-delete'
            href:
                # Zur Info: Die konkreten Parameter setzt kontext-bezogen pages/index.php

```
Natürlich muss dann für die Zugriffsfechte neben dem Detail-Zugriffsrecht (z.B. `geolocation[mapset]`) immer auch das Recht 'geolocation[]` in die Rolle aufgenommen werden. Ob das so strukturell richtig ist, weiß ich nicht. Hab das nie ganz verstanden. 

Probier die Lösung mal aus, bitte. Ich würde es dann so in das nächste Release aufnehmen.

Wenn das mal jemand mit Kenne richtig glatt zieht und eleganter gestaltet: gerne nen PR ("haaaaloooo, hört mich mich jemand?)
