### ISSUE TITLE
Umstellung auf "YForm ohne Plugins"

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#176]
Bisher habe ich nur vier Stellen mit Anpassungsbedarf gefunden:

**pages/yform.php**
```php
...
include rex_path::plugin('yform', 'manager', 'pages/data_edit.php');
...
```
Die Zeile muss geändet werden in
```php
...
include rex_path::addon('yform','pages/manager.data_edit.php');
...
```

**package.yml**
```yml
version: 2.5.0             => Wegen Inkomtatibilität/BC auf 3.0 ändern
requires:
    php:
        version: '^8'      => auf die von YForm dem geforderten Redaxo benötigte Version, mind. aber 8.1 ändern
    redaxo: '^5.14.0'      => auf die von YForm benötigte Version, mind. aber 5.14 anpassen
    packages:
        cronjob: '^2.8.0'  => entsprechend der Redaxo-Version, min. 2.8 anpassen
        yform: '^4.0.0'    => auf die YForm-Version anpassen
```

**lib/Layer.php**
https://github.com/FriendsOfREDAXO/geolocation/blob/ab6f578c481c3523b5f6b1394f277902b3795b6d/lib/Layer.php#L394-L412

Da eh ein BC vorliegt kann die Fallunterscheifung wegfallen und damit auch der Aufruf von `rex_path::plugin`

**lib/Mapset.php**
https://github.com/FriendsOfREDAXO/geolocation/blob/ab6f578c481c3523b5f6b1394f277902b3795b6d/lib/Mapset.php#L315-L333

Da eh ein BC vorliegt kann die Fallunterscheifung wegfallen und damit auch der Aufruf von `rex_path::plugin`
