### ISSUE TITLE
Konflikt mit yform_geo_osm

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#30]
Beide bringen Leaflet mit, das kracht aus JS-Ebene. Würde sich mit #28  und einer neuen Version von yform_geo_osm lösen. Könnte man b.a.w. in der package.yml lösen:

```yml
conflicts:
    packages:
        yform_geo_osm: '>0.0.0'
```

Und Hinweise in der README.md, docs/install.md sowie im Installer.
